### ISSUE TITLE
Implement SemVer2 (or another version scheme)

### ISSUE THREAD

**Issue by christoph-schlosser** [mauricesvay/php-facedetection#21]
It'd help a lot if you could tag at least a 0.* version to rely on. We'd rather have no `dev-master` dependencies :wink:

**Comment by mauricesvay** [comment]
Hi Christoph,

I've tagged the current version as 0.0.1 and published it to packagist here https://packagist.org/packages/mauricesvay/php-facedetection

Is that ok for you?

**Comment by christoph-schlosser** [comment]
That is perfectly fine, thank you very much!
