### ISSUE TITLE
Just a wish

### ISSUE THREAD

**Issue by kamaroly** [mauricesvay/php-facedetection#27]
@mauricesvay thank you for such a great library , would you be so kind to put some comments in the codes especially where there is a lot of math to give a hint of why numbers like 0.12 are chose ?

**Comment by muyncky** [comment]
+1 for more comments on this beautiful piece of nature. If possible, provide comments for every line, by means of saying...

**Comment by mauricesvay** [comment]
Hi,

I actually don't know what the code is actually doing, I just ported it from JavaScript to PHP.
I think the original author said that it is an implementation of Viola-Jones.
